//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelManagment
{
    using System;
    using System.Collections.Generic;

    public partial class FillOnCard
    {
        public int Id { get; set; }
        public int WaybillId { get; set; }
        public string DriverName { get; set; }

        private decimal _fuelCount;

        public decimal FuelCount { get; set; }

        private decimal _diselPrice;
        public decimal DiselPrice { get; set; }

        public System.DateTime Date { get; set; }
        public string VehicleLicensePlate { get; set; }
        public int GasStationId { get; set; }
        public decimal Amount { get; private set; }
        public GasStation GasStation { get; set; }
        public Waybill Waybill { get; set; }

        public void SetProps()
        {
            Amount = FuelCount * DiselPrice;
            DriverName = Waybill.Driver.Name;
            VehicleLicensePlate = Waybill.Vehicle.LicensePlate;
            DiselPrice = GasStation.FuelCompany.DiselPrice;
        }
    }
}