//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelManagment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Waybill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Waybill()
        {
            this.FillOnCards = new HashSet<FillOnCard>();
        }
    
        public int Id { get; set; }
        public int Number { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime DateOfCompletion { get; set; }
        public int VehicleId { get; set; }
        public int DriverId { get; set; }
    
        public virtual Driver Driver { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FillOnCard> FillOnCards { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
